homepage:
    pattern:  /
    defaults: { _controller: CMSBaseBundle:Frontpage:index }

hello:
    pattern:  /haithar
    defaults: { _controller: CMSBaseBundle:Frontpage:hello }

page:
    pattern:  /page/{slug}
    defaults: { _controller: CMSBaseBundle:Page:show }
    
_security_login:
    pattern:  /login
    defaults: { _controller: CMSBaseBundle:Security:login }
    
_security_check:
    pattern:  /login_check
    
_security_logout:
    pattern:  /logout
    