homepage:
    pattern:  /
    defaults: { _controller: CMSBaseBundle:Frontpage:index }

hello:
    pattern:  /haithar
    defaults: { _controller: CMSBaseBundle:Frontpage:hello }

page:
    pattern:  /page/{slug}
    defaults: { _controller: CMSBaseBundle:Page:show }
    