homepage:
    pattern:  /
    defaults: { _controller: CMSBase:Frontpage:index }

hello:
    pattern:  /haithar
    defaults: { _controller: CMSBase:Frontpage:hello }

page:
    pattern:  /page/{slug}
    defaults: { _controller: CMSBase:Page:show }
    