homepage:
    pattern:  /
    defaults: { _controller: CMSBaseBundle:Frontpage:index }

hello:
    pattern:  haithar
    defaults: { _controller: CMSBaseBundle:Frontpage:hello }

page:
    pattern:  page/{slug}.{_format}
    defaults: { _controller: CMSBaseBundle:Page:show, _format: html }
    
edit_page:
    pattern:  admin/page/{slug}/edit.{_format}
    defaults: { _controller: CMSBaseBundle:Page:edit, _format: html }
    
delete_page:
    pattern:  admin/page/{slug}/delete.{_format}
    defaults: { _controller: CMSBaseBundle:Page:delete, _format: html }
    
news:
    pattern:  news.{_format}
    defaults: { _controller: CMSBaseBundle:News:index, _format: html }
    
show_news:
    pattern:  news/article/{slug}.{_format}
    defaults: { _controller: CMSBaseBundle:News:show, _format: html }
    
edit_news:
    pattern:  admin/news/{slug}/edit.{_format}
    defaults: { _controller: CMSBaseBundle:News:edit, _format: html }
        
delete_news:
    pattern:  admin/news/{slug}/delete.{_format}
    defaults: { _controller: CMSBaseBundle:News:delete, _format: html }

image_upload:
    pattern:  admin/image/upload.{_format}
    defaults: { _controller: image_gallery_controller:uploadAction, _format: json }
