imports:
    - { resource: parameters.php }
    - { resource: security.yml }
    CMSBaseBundle:
        resource: @CMSBaseBundle/Resources/config/menu.yml  
    UserBundle:
        resource: @UserBundle/Resources/config/menu.yml  
        
framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: master
        connections:
            master:
               driver:   %database.master.driver%
               host:     %database.master.host%
               port:     %database.master.port%
               dbname:   %database.master.name%
               user:     %database.master.user%
               password: %database.master.pass%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default: 
                mappings:
                    CMSBaseBundle: 
                        type: yml
                        dir: Resources/config/doctrine
                    UserBundle: 
                        type: yml
                        dir: Resources/config/doctrine

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# Enable menu helper
knplabs_menu:
    templating: true