# includes
CMSBaseBundle:
    resource: "@CMSBaseBundle/Resources/config/routing.yml"
UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
SiteManagerBundle:
    resource: "@SiteManagerBundle/Resources/config/routing.yml"
