# app/config/security.yml
security:  
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    providers:
        default_provider:
            providers: [in_memory, main]
        main:
            entity: { class: GoGreat\CMSBaseBundle\Entity\User, property: username }
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern:      .*
            form_login:
                check_path:   /login_check
                login_path:   /login                
                use_referer:  false
            logout:       true
            anonymous:    true

    access_control:
        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Login routes        
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY } # for the case of a failed login
       
        # Secured Admin  
        - { path: ^/admin/, role: ROLE_ADMIN }
        
        # Secured part of the site 
        - { path: ^/page/.*, role: ROLE_USER }
        
        # 
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPERADMIN:  ROLE_ADMIN