<?php

namespace GoGreat\CMSBaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends EntityRepository
{
	public function findAll()
	{		
		$qb = $this->createQueryBuilder('mi');
		$qb->add('orderBy', 'mi.weight ASC');
		
		return $qb->getQuery()->getResult();
	}
}