<?php

namespace GoGreat\CMSBaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends EntityRepository
{
	public function findAll()
	{		
		$qb = $this->createQueryBuilder('mi');
		$qb->add('orderBy', 'mi.weight ASC');
		
		return $qb->getQuery()->getResult();
	}
	
	/**
	 * persist an instance of MenuItem with the entity_manager
	 * 
	 * @param MenuItem $item
	 */
	public function persist(MenuItem $item)
	{		
		$em = $this->getEntityManager();
		
		$identifier = $item->getIdentifier();
		$generated = (!$identifier);
		
		if($generated)				
			$identifier = $item->fixIdentifier();

		if(!$generated && ($found = $this->findOneByIdentifier($identifier)) && ($item != $found))
			return false;
		else if($generated)
			while($this->findOneByIdentifier($identifier))
				$identifier = $item->fixIdentifier(true);
				
		$item->setIdentifier($identifier);
		
		$em->persist($item);
		$em->flush();
	}
}