<?php

namespace GoGreat\CMSBaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsArticleRepository extends EntityRepository
{
	/**
	 * persist an instance of NewsArticle with the entity_manager
	 * 
	 * @param NewsArticle $news
	 */
	public function persist(NewsArticle $news)
	{		
		if(!$news->getPublishedDate()) {
			$news->setPublishedDate(new \DateTime());
		}
		
		$em = $this->getEntityManager();
		$em->persist($news);
	}
	
	/**
	 * remove an instance of NewsArticle with the entity_manager
	 * 
	 * @param NewsArticle $news
	 */
	public function remove(NewsArticle $news)
	{		
		$em = $this->getEntityManager();
		$em->remove($news);
	}
}