GoGreat\CMSBaseBundle\Entity\Block:
  type: entity
  table: block
  repositoryClass: GoGreat\CMSBaseBundle\Entity\BlockRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 45
      fixed: false
      nullable: true
    slug:
      type: string
      length: 45
      fixed: false
      nullable: true
    content:
      type: text
      fixed: false
      nullable: true 
  manyToOne:
    page:
      targetEntity: Page
      cascade: { }
      mappedBy: null
      inversedBy: block
      joinColumns:
        page_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
