GoGreat\UserBundle\Entity\User:
  type: entity
  table: user
  repositoryClass: GoGreat\UserBundle\Entity\UserRepository
  fields:
    username:
      id: true
      type: string
      length: 45
      fixed: false
      nullable: true
    password:
      type: string
      length: 45
      fixed: false
      nullable: true
    email:
      type: string
      length: 100
      fixed: false
      nullable: true
    roles:
      type: array
      nullable: true
  oneToMany:
    adresses:
      targetEntity: Address
      mappedBy: address
  lifecycleCallbacks: {  }