GoGreat\ServerBaseBundle\Entity\Domain:
  type: entity
  table: domain
  repositoryClass: GoGreat\ServerBaseBundle\Entity\DomainRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    domain:
      type: string
      length: 255
      fixed: false
      nullable: false
  manyToOne:
    website:
      targetEntity: Website
      inversedBy: domains
      joinColumns:
        website_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
