GoGreat\ServerBaseBundle\Entity\Module:
  type: entity
  table: module
  repositoryClass: GoGreat\ServerBaseBundle\Entity\ModuleRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false  
  manyToMany:
    websites:
      targetEntity: Website
      joinTable: 
        name: websites_modules
        joinColumns:
          website_id:
            referencedColumnName: id
        inverseJoinColumns:
          module_id:
            referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
