site_new:
    pattern:  /site/new
    defaults: { _controller: SiteManagerBundle:SiteManager:new }
    
site_edit:
    pattern:  /site/edit/{id}
    defaults: { _controller: SiteManagerBundle:SiteManager:edit }
    
site_overview:
    pattern:  /site/overview
    defaults: { _controller: SiteManagerBundle:SiteManager:overview }
